ConfigUrl = ""

[Http]
  CORES = "*"
  Port = 80
  Path = "/"
  MaxBufferSize = 10485760
  JwtSecret = "DhSQekDq1XctftfH5LnX6V5pmJMTaOOM"
  AutoAuth = true

[[Redis]]
  Name = "default"
  Username = ""
  Password = "mXJLFAt3y47woLF5AkNiKs3ug1D0yWz8"
  Host = "keydb.lan"
  Port = 6379
  DB = 1

[[HttpRPC]]
  Name = "doptime"
  UrlBase = "https://api.doptime.com"
  Jwt = ""

[Settings]
  LogLevel = 1
  SUToken = "HboVsNf0bMa1fYq9HXr02SaRD7yz3gyj"