CONFIG_URL = "abc"
ConfigUrl = ""

[Http]
DangerousAutoWhitelist = true
CORES = "*"
JwtSecret = "DhSQekDq1XctftfH5LnX6V5pmJMTaOOM"
MaxBufferSize = 10485760
Path = "/"
Port = 81

[[HttpRPC]]
Jwt = "ther's no such jwt"
Name = "doptime"
UrlBase = "https://api.doptime.com"

[[Redis]]
DB = 0
Host = "dragonflyprojects.lan"
Name = "default"
Password = "XWkHqup04Gcm7Plieh5x"
Port = 6379
Username = ""

[[Redis]]
DB = 5
Host = "dragonflyprojects.lan"
Name = "learnbychoose"
Password = "XWkHqup04Gcm7Plieh5x"
Port = 6379
Username = ""

[[Redis]]
DB = 0
Host = "dragonflyprojects.lan"
Name = "dragonflyprojects"
Password = "XWkHqup04Gcm7Plieh5x"
Port = 6379
Username = ""

[[Redis]]
DB = 2
Host = "dragonflyprojects.lan"
Name = "Catalogs"
Password = "XWkHqup04Gcm7Plieh5x"
Port = 6379
Username = ""

[[Redis]]
DB = 2
Host = "dragonflyprojects.lan"
Name = "usecase"
Password = "XWkHqup04Gcm7Plieh5x"
Port = 6379
Username = ""


# [[Redis]]
# DB = 2
# Host = "keydb.lan"
# Name = "def6379"
# Password = "mXJLFAt3y47woLF5AkNiKs3ug1D0yWz8"
# Port = 6379
# Username = ""

[Settings]
LogLevel = 1
SUToken = "HboVsNf0bMa1fYq9HXr02SaRD7yz3gyj"
[[EvoRealms]]
Enable = false
Name = "RedisDB"
RootPath = "/Users/yang/doptime/redisdb"
GitIgnore = ".*,*.mod,*.sum,*.doc,*.git,*.idea,*.vscode,*.evolab"

[[EvoRealms]]
Name = "learniversebackend"
Enable = true
RootPath = "/Users/yang/learn-by-choose-goserver"
GitIgnore = ".*,*.mod,*.sum,*.doc,*.git,*.idea,*.vscode,*.evolab"

[[EvoRealms]]
Name = "pickingmap"
Enable = true
RootPath = "/Users/yang/pickingmap"
GitIgnore = ".*,*.mod,*.sum,*.doc,*.git,*.idea,*.vscode,*.evolab"

[[EvoRealms]]
Name = "learniverseweb"
Enable = true
RootPath = "/Users/yang/doptime/evolab/web/app/learn-by-choose"
GitIgnore = ".*,*.mod,*.sum,*.doc,*.git,*.idea,*.vscode,*.evolab"

[[EvoRealms]]
Name = "doptimeutils"
Enable = false
RootPath = "/Users/yang/doptime/doptime/utils"
GitIgnore = ".*,.excalidraw,.png,.mdx,*.go,.git,.idea,.vscode,3rd_lang,DockerFile,test,.evolab,vars,"

[[EvoRealms]]
Name = "doptime"
Enable = false
RootPath = "/Users/yang/doptime/doptime"
GitIgnore = ".*,.excalidraw,.png,.mdx,.git,.idea,.vscode,3rd_lang,DockerFile,test,.evolab,vars,"

[[EvoRealms]]
Name = "aircraft"
Enable = false
RootPath = "/Users/yang/aircraft"
GitIgnore = ".*,.git,.idea,.vscode,.evolab"

[[EvoRealms]]
Name = "aircraftwing"
Enable = false
RootPath = "/Users/yang/aircraft/wing"
GitIgnore = ".*,expired_ideas.md,.git,.idea,.vscode,.evolab"

[[EvoRealms]]
Name = "btctrade"
Enable = false
RootPath = "/Users/yang/btctrade"
GitIgnore = ".*,expired_ideas.md,.git,.idea,.vscode,.evolab,.ignored"

[[EvoRealms]]
Name = "doptime-client"
Enable = false
RootPath = "/Users/yang/doptime/doptime-client"
GitIgnore = ".*,package-lock.json,.git,.idea,.vscode,.evolab,.ignored,node_modules,lib"
